# generated by datamodel-codegen:
#   filename:  v3

from __future__ import annotations

from pydantic import BaseModel


class Info(BaseModel):
    """
    Info contains versioning information. how we'll want to distribute that information.
    """

    buildDate: str
    compiler: str
    gitCommit: str
    gitTreeState: str
    gitVersion: str
    goVersion: str
    major: str
    minor: str
    platform: str
