pingPong:
  namespace: "ping-pong"
  image: "docker.io/library/busybox:stable"
  replicas: 2
  pongPort: 80
  call: "hostname"
  response: "hostname"
  interval: 15

ubuntu:
  image: "ubuntu:22.04"

python:
  image: "python:3.11"
  packages:
    - ipython
    - kubernetes

kuard:
  namespace: kuard
  image: "gcr.io/kuar-demo/kuard-amd64:blue"
