{{ if ne .Values.ubuntu.namespace "default" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ubuntu.namespace }}
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: {{ .Values.ubuntu.namespace }}
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: {{ .Values.ubuntu.image }}
        command: ["sleep", "infinity"]
